import random
a = random.randint(1, 10)
b = random.randint(1, 10)
c = random.randint(1, 10)
d = random.randint(1, 10)
e = random.randint(1, 10)
t = (a, b, c, e)
m = max(t)
n = min(t)
print(f'A Tupla gerada dessa vez foi a seguinte: {t}')
print(f'O maior valor encontrado na tupla foi: {m}')
print(f'O menor valor encontrado na tupla foi: {n}')
