a=int(input('Digite:'))
print('Segue a tabela de {}:'.format(a))
print('{}X1={}'. format(a,a*1))
print('{}X2={}'.format(a,a*2))
print('{}X3={}'.format(a,a*3))
print('{}X4={}'.format(a,a*4))
print('{}X5={}'.format(a,a*5))
print('{}X6={}'.format(a,a*6))
print('{}X7={}'.format(a,a*7))
print('{}X8={}'.format(a,a*8))
print('{}X9={}'.format(a,a*9))